services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    container_name: todo-backend
    restart: always
    ports:
      - "8002:8000"
    networks:
      - app_network

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    container_name: todo-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8001:5173"
    networks:
      - app_network

networks:
  app_network:
    name: todo-network
    driver: bridge
